/**
 * Granular Permission Constants for TrialGuard AI Role-Based Access Control (RBAC)
 */

export const PERMISSIONS = {
  // Trial & Protocol
  VIEW_TRIAL: "VIEW_TRIAL",
  MANAGE_PROTOCOL: "MANAGE_PROTOCOL",
  
  // Sites
  VIEW_ALL_SITES: "VIEW_ALL_SITES",
  VIEW_ASSIGNED_SITE: "VIEW_ASSIGNED_SITE",
  VIEW_SITE_RISK: "VIEW_SITE_RISK",
  VIEW_TRIAL_RISK: "VIEW_TRIAL_RISK",
  
  // Patients & Data Integrity
  VIEW_PATIENTS: "VIEW_PATIENTS",
  VIEW_ALL_PATIENTS: "VIEW_ALL_PATIENTS",
  VIEW_OWN_SITE_PATIENTS: "VIEW_OWN_SITE_PATIENTS",
  MANAGE_PATIENT_DATA: "MANAGE_PATIENT_DATA",
  EDIT_PATIENT_DATA: "EDIT_PATIENT_DATA",
  
  // Deviations
  VIEW_DEVIATIONS: "VIEW_DEVIATIONS",
  CREATE_DEVIATION: "CREATE_DEVIATION",
  EDIT_DEVIATION: "EDIT_DEVIATION",
  REVIEW_DEVIATION: "REVIEW_DEVIATION",
  RESOLVE_DEVIATION: "RESOLVE_DEVIATION",
  RUN_COMPLIANCE_ANALYSIS: "RUN_COMPLIANCE_ANALYSIS",
  
  // CAPA Lifecycle
  VIEW_CAPA: "VIEW_CAPA",
  CREATE_CAPA: "CREATE_CAPA",
  EDIT_CAPA: "EDIT_CAPA",
  ASSIGN_CAPA: "ASSIGN_CAPA",
  RESPOND_TO_CAPA: "RESPOND_TO_CAPA",
  APPROVE_CAPA: "APPROVE_CAPA",
  UPDATE_CAPA_STATUS: "UPDATE_CAPA_STATUS",
  
  // Reporting & Export
  VIEW_REPORTS: "VIEW_REPORTS",
  GENERATE_REPORTS: "GENERATE_REPORTS",
  EXPORT_REPORTS: "EXPORT_REPORTS",
  
  // Administration & Governance
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  VIEW_AUDIT_LOG: "VIEW_AUDIT_LOG",
  VIEW_NOTIFICATIONS: "VIEW_NOTIFICATIONS"
};
